# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd5d15ebda22ca5fd87cdbf7fe07db38cf4fe9396513bdc91b9f154e107423e18d8b5cb065c09d3aa6a5b1d9a50642b2b7f28980a991785d1bab725e4a870c46

test:
  secret_key_base: 57775db034db6f9c007fc2f164dd8ed8c61550627537cd5d38f42ba0e20e00571749cc8f1dd3cc1a4d7a223fc888ca046f81481d1606eb22d5299ea9ff111cf5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
